# Github workflow to compile latex and deploy the pdf to an orphan branch.
# The latest compiled pdf is at available at e.g.
# https://github.com/dgerosa/reponame/blob/build/filename.pdf
# Davide Gerosa (2021) https://github.com/dgerosa

name: writeapaper

on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    env:
      # Edit here with the names of your latex file and directory (can use ".")
      DIR: documenti 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install TeXlive
        run: sudo apt-get update && sudo apt-get install texlive 
      - name: LaTeX compile script
        run: sh ./compile.sh
      - name: move
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/ ./github_artifacts/
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.DIR}}
          path: ./github_artifacts
  
